NAMES = [
    # Harry Potter
    "Harry Potter",
    "Hermione Granger",
    "Ron Weasley",
    "Albus Dumbledore",
    "Severus Snape",
    "Lord Voldemort",
    "Draco Malfoy",
    "Luna Lovegood",
    "Rubeus Hagrid",
    "Sirius Black",
    "Bellatrix Lestrange",
    "Lucius Malfoy",
    "Ginny Weasley",
    "Neville Longbottom",
    "Cho Chang",
    "Cedric Diggory",
    "Remus Lupin",
    "Nymphadora Tonks",
    "Molly Weasley",
    "Arthur Weasley",
    "Fred Weasley",
    "George Weasley",
    "Percy Weasley",
    "Charlie Weasley",
    "Bill Weasley",
    "Dean Thomas",
    "Seamus Finnigan",
    "Parvati Patil",
    "Lavender Brown",

    # Rick and Morty
    "Rick Sanchez",
    "Morty Smith",
    "Summer Smith",
    "Beth Smith",
    "Jerry Smith",
    "Mr. Poopybutthole",
    "Birdperson",
    "Squanchy",
    "Krombopulos Michael",
    "Abradolf Lincoler",
    "Unity",
    "Evil Morty",
    "Pickle Rick",
    "Beth Clone",
    "Summer Clone",
    "Morty Clone",
    "Planetina",
    "Tammy Guetermann",
    "Jaguar",
    "Noob-Noob",

    # Game of Thrones
    "Daenerys Targaryen",
    "Jon Snow",
    "Tyrion Lannister",
    "Cersei Lannister",
    "Arya Stark",
    "Sansa Stark",
    "Bran Stark",
    "Jaime Lannister",
    "Brienne of Tarth",
    "Samwell Tarly",
    "Jorah Mormont",
    "The Hound",
    "Petyr Baelish",
    "Varys",
    "Littlefinger",
    "Olenna Tyrell",
    "Margaery Tyrell",
    "Loras Tyrell",
    "Tormund Giantsbane",
    "Melisandre",
    "Davos Seaworth",
    "Stannis Baratheon",
    "Renly Baratheon",
    "Robert Baratheon",
    "Catelyn Stark",
    "Robb Stark",
    "Theon Greyjoy",
    "Yara Greyjoy",
    "Ramsay Bolton",
    "Roose Bolton",
]
